import { createThemeContract } from "@vanilla-extract/css";

export const vars = createThemeContract({
  color: {
    bg: {
      app: "",
      canvas: "",
      panel: "",
      elevated: "",
      hover: "",
      lowest: "",
      bright: "",
    },
    text: {
      primary: "",
      secondary: "",
      muted: "",
      inverse: "",
    },
    accent: {
      primary: "",
      primaryDim: "",
      primaryHover: "",
      secondary: "",
      secondaryDim: "",
      secondaryContainer: "",
      tertiary: "",
      tertiaryDim: "",
      cyan: "",
      accent: "",
      accentDim: "",
      accentGlow: "",
    },
    onColor: {
      primary: "",
      secondary: "",
      tertiary: "",
    },
    state: {
      created: "",
      planning: "",
      running: "",
      cacheHit: "",
      completed: "",
      paused: "",
      cancelled: "",
      failed: "",
    },
    mod: {
      image: "",
      video: "",
      audio: "",
      text: "",
      model: "",
      system: "",
    },
    success: { base: "", text: "" },
    warning: { base: "", text: "" },
    error: { base: "", text: "" },
    scrim: "",
    shadowElevation: "",
    outline: {
      base: "",
      variant: "",
    },
  },
  font: {
    headline: "",
    ui: "",
    code: "",
    size: {
      kbd: "",
      caption: "",
      bodySm: "",
      body: "",
      bodyLg: "",
      headingSm: "",
      heading: "",
      headingLg: "",
      display: "",
    },
    weight: {
      regular: "",
      medium: "",
      semibold: "",
      bold: "",
      black: "",
    },
    lineHeight: {
      tight: "",
      normal: "",
      relaxed: "",
    },
  },
  space: {
    insetXs: "",
    insetSm: "",
    insetMd: "",
    insetLg: "",
    insetXl: "",
    gapXs: "",
    gapSm: "",
    gapMd: "",
    gapLg: "",
    gapXl: "",
  },
  radius: {
    control: "",
    card: "",
    panel: "",
    container: "",
    full: "",
  },
  control: {
    heightSm: "",
    heightMd: "",
    heightLg: "",
  },
  icon: {
    sm: "",
    md: "",
    lg: "",
  },
  motion: {
    durationInstant: "",
    durationFast: "",
    durationNormal: "",
    durationSlow: "",
    durationSlower: "",
    easingDefault: "",
    easingSpring: "",
    easingExit: "",
  },
  shadow: {
    sm: "",
    md: "",
    lg: "",
    glowAccent: "",
  },
  density: {
    d1: "", d2: "", d3: "", d4: "", d5: "", d6: "", d7: "", d8: "", d9: "",
    padCard: "",
    padSection: "",
    rowH: "",
    gapCard: "",
  },
  card: {
    bg: "",
    border: "",
    shadow: "",
    backdrop: "",
  },
  chip: {
    height: "",
    dot: "",
    padX: "",
    gap: "",
    fontSize: "",
  },
  focus: {
    ringWidth: "",
    offset: "",
  },
  text: {
    eyebrow: "",
    chip: "",
    sectionTitle: "",
  },
  z: {
    base: "",
    dropdown: "",
    drawer: "",
    modal: "",
    toast: "",
    overlay: "",
  },
});
