import { createThemeContract } from "@vanilla-extract/css";

export const vars = createThemeContract({
  color: {
    bg: { app: "", canvas: "", panel: "", elevated: "", hover: "" },
    text: { primary: "", secondary: "", muted: "", inverse: "" },
    accent: { primary: "", primaryHover: "", secondary: "", cyan: "" },
    state: {
      created: "",
      planning: "",
      running: "",
      cacheHit: "",
      completed: "",
      paused: "",
      cancelled: "",
      failed: "",
    },
    mod: { image: "", video: "", audio: "", text: "", model: "", system: "" },
    success: { base: "", text: "" },
    warning: { base: "", text: "" },
    error: { base: "", text: "" },
    border: { subtle: "", strong: "" },
  },
  font: {
    ui: "",
    code: "",
    size: {
      caption: "",
      bodySm: "",
      body: "",
      bodyLg: "",
      headingSm: "",
      heading: "",
      headingLg: "",
      display: "",
    },
    weight: { regular: "", medium: "", semibold: "", bold: "" },
    lineHeight: { tight: "", normal: "", relaxed: "" },
  },
  space: {
    insetXs: "",
    insetSm: "",
    insetMd: "",
    insetLg: "",
    insetXl: "",
    gapXs: "",
    gapSm: "",
    gapMd: "",
    gapLg: "",
    gapXl: "",
  },
  radius: { control: "", card: "", panel: "", container: "", full: "" },
  control: { heightSm: "", heightMd: "", heightLg: "" },
  icon: { sm: "", md: "", lg: "" },
  motion: {
    durationInstant: "",
    durationFast: "",
    durationNormal: "",
    durationSlow: "",
    durationSlower: "",
    easingDefault: "",
    easingSpring: "",
    easingExit: "",
  },
  shadow: { sm: "", md: "", lg: "" },
  z: { base: "", dropdown: "", drawer: "", modal: "", toast: "", overlay: "" },
});
