import { createTheme } from "@vanilla-extract/css";
import { vars } from "./contract.css";
import { color, spacing, radii, typography, motion, density, cardStyle, accentMode } from "../tokens/primitives";

export const darkTheme = createTheme(vars, {
  color: {
    bg: {
      app: color.surface.base,
      canvas: color.surface.base,
      panel: color.surface.containerLow,
      elevated: color.surface.containerHigh,
      hover: color.surface.containerHighest,
      lowest: color.surface.containerLowest,
      bright: color.surface.bright,
    },
    text: {
      primary: color.onSurface.base,
      secondary: color.onSurface.variant,
      muted: color.outline.base,
      inverse: color.primary.onPrimary,
    },
    accent: {
      primary: color.primary.base,
      primaryDim: color.primary.dim,
      primaryHover: color.primary.container,
      secondary: color.secondary.base,
      secondaryDim: color.secondary.dim,
      secondaryContainer: color.secondary.container,
      tertiary: color.tertiary.base,
      tertiaryDim: color.tertiary.dim,
      cyan: "#06B6D4",
      accent: accentMode.primary.accent,
      accentDim: accentMode.primary.accentDim,
      accentGlow: accentMode.primary.accentGlow,
    },
    onColor: {
      primary: color.primary.onPrimary,
      secondary: color.secondary.onSecondary,
      tertiary: color.tertiary.onTertiary,
    },
    state: {
      created: color.outline.base,
      planning: color.primary.base,
      running: color.primary.base,
      cacheHit: "#06B6D4",
      completed: color.acidGreen,
      paused: color.warning.base,
      cancelled: color.outline.base,
      failed: color.error.base,
    },
    mod: {
      image: color.modality.image,
      video: color.modality.video,
      audio: color.modality.audio,
      text: color.modality.text,
      model: color.modality.model,
      system: color.modality.system,
    },
    success: { base: color.acidGreen, text: "#BBF7D0" },
    warning: { base: color.warning.base, text: color.warning.text },
    error: { base: color.error.base, text: "#FECACA" },
    scrim: "rgba(0, 0, 0, 0.55)",
    shadowElevation: "rgba(0, 0, 0, 0.4)",
    outline: {
      base: color.outline.base,
      variant: color.outline.variant,
    },
  },
  font: {
    headline: typography.family.headline,
    ui: typography.family.body,
    code: typography.family.code,
    size: {
      kbd: typography.size[10],
      caption: typography.size[11],
      bodySm: typography.size[12],
      body: typography.size[13],
      bodyLg: typography.size[14],
      headingSm: typography.size[16],
      heading: typography.size[20],
      headingLg: typography.size[24],
      display: typography.size[32],
    },
    weight: {
      regular: typography.weight[400],
      medium: typography.weight[500],
      semibold: typography.weight[600],
      bold: typography.weight[700],
      black: typography.weight[900],
    },
    lineHeight: {
      tight: typography.lineHeight[1.2],
      normal: typography.lineHeight[1.5],
      relaxed: typography.lineHeight[1.6],
    },
  },
  space: {
    insetXs: spacing[2],
    insetSm: spacing[3],
    insetMd: spacing[4],
    insetLg: spacing[6],
    insetXl: spacing[8],
    gapXs: spacing[2],
    gapSm: spacing[4],
    gapMd: spacing[6],
    gapLg: spacing[8],
    gapXl: spacing[12],
  },
  radius: {
    control: radii[6],
    card: radii[10],
    panel: radii[14],
    container: radii[16],
    full: radii.full,
  },
  control: {
    heightSm: "28px",
    heightMd: "32px",
    heightLg: "40px",
  },
  icon: {
    sm: "14px",
    md: "16px",
    lg: "20px",
  },
  motion: {
    durationInstant: motion.duration.instant,
    durationFast: motion.duration.fast,
    durationNormal: motion.duration.normal,
    durationSlow: motion.duration.slow,
    durationSlower: motion.duration.slower,
    easingDefault: motion.easing.default,
    easingSpring: motion.easing.spring,
    easingExit: motion.easing.exit,
  },
  shadow: {
    sm: "0 2px 4px rgba(0,0,0,0.4)",
    md: "0 4px 12px rgba(0,0,0,0.5)",
    lg: "0 12px 32px rgba(0,0,0,0.6)",
    glowAccent: `0 0 24px ${accentMode.primary.accentGlow}`,
  },
  density: {
    d1: density.cozy.d1, d2: density.cozy.d2, d3: density.cozy.d3, d4: density.cozy.d4,
    d5: density.cozy.d5, d6: density.cozy.d6, d7: density.cozy.d7, d8: density.cozy.d8, d9: density.cozy.d9,
    padCard: density.cozy.padCard,
    padSection: density.cozy.padSection,
    rowH: density.cozy.rowH,
    gapCard: density.cozy.gapCard,
  },
  card: {
    bg: cardStyle.flat.bg,
    border: cardStyle.flat.border,
    shadow: cardStyle.flat.shadow,
    backdrop: cardStyle.flat.backdrop,
  },
  chip: {
    height: spacing[12],
    dot: spacing[3],
    padX: spacing[5],
    gap: spacing[3],
    fontSize: typography.size[11],
  },
  focus: {
    ringWidth: spacing[1],
    offset: spacing[1],
  },
  text: {
    eyebrow: typography.size[11],
    chip: typography.size[11],
    sectionTitle: typography.size[20],
  },
  z: {
    base: "0",
    dropdown: "100",
    drawer: "200",
    modal: "300",
    toast: "400",
    overlay: "500",
  },
});
