import { createTheme } from "@vanilla-extract/css";
import { vars } from "./contract.css";
import { color, spacing, radii, typography, motion } from "../tokens/primitives";

export const darkTheme = createTheme(vars, {
  color: {
    bg: {
      app: color.navy[900],
      canvas: color.navy[800],
      panel: color.navy[700],
      elevated: color.navy[600],
      hover: color.navy[500],
    },
    text: {
      primary: color.navy[50],
      secondary: color.navy[100],
      muted: color.navy[200],
      inverse: color.navy[900],
    },
    accent: {
      primary: color.blue[400],
      primaryHover: color.blue[500],
      secondary: color.violet[400],
      cyan: color.cyan[400],
    },
    state: {
      created: color.slate[400],
      planning: color.violet[400],
      running: color.blue[400],
      cacheHit: color.cyan[400],
      completed: color.green[400],
      paused: color.amber[400],
      cancelled: color.slate[400],
      failed: color.red[400],
    },
    mod: {
      image: color.modality.image,
      video: color.modality.video,
      audio: color.modality.audio,
      text: color.modality.text,
      model: color.modality.model,
      system: color.modality.system,
    },
    success: { base: color.green[400], text: color.green[400] },
    warning: { base: color.amber[400], text: color.amber[400] },
    error: { base: color.red[400], text: color.red[400] },
    border: {
      subtle: color.navy[400],
      strong: color.navy[300],
    },
  },
  font: {
    ui: typography.family.ui,
    code: typography.family.code,
    size: {
      caption: typography.size[11],
      bodySm: typography.size[12],
      body: typography.size[13],
      bodyLg: typography.size[14],
      headingSm: typography.size[16],
      heading: typography.size[20],
      headingLg: typography.size[24],
      display: typography.size[32],
    },
    weight: {
      regular: typography.weight[400],
      medium: typography.weight[500],
      semibold: typography.weight[600],
      bold: typography.weight[700],
    },
    lineHeight: {
      tight: typography.lineHeight[1.2],
      normal: typography.lineHeight[1.5],
      relaxed: typography.lineHeight[1.6],
    },
  },
  space: {
    insetXs: spacing[1],
    insetSm: spacing[3],
    insetMd: spacing[4],
    insetLg: spacing[6],
    insetXl: spacing[8],
    gapXs: spacing[2],
    gapSm: spacing[4],
    gapMd: spacing[6],
    gapLg: spacing[8],
    gapXl: spacing[12],
  },
  radius: {
    control: radii[6],
    card: radii[10],
    panel: radii[14],
    container: radii[16],
    full: radii.full,
  },
  control: {
    heightSm: "28px",
    heightMd: "32px",
    heightLg: "40px",
  },
  icon: {
    sm: "14px",
    md: "16px",
    lg: "20px",
  },
  motion: {
    durationInstant: motion.duration.instant,
    durationFast: motion.duration.fast,
    durationNormal: motion.duration.normal,
    durationSlow: motion.duration.slow,
    durationSlower: motion.duration.slower,
    easingDefault: motion.easing.default,
    easingSpring: motion.easing.spring,
    easingExit: motion.easing.exit,
  },
  shadow: {
    sm: "0 1px 3px rgba(0, 0, 0, 0.4)",
    md: "0 4px 8px rgba(0, 0, 0, 0.45)",
    lg: "0 10px 20px rgba(0, 0, 0, 0.5)",
  },
  z: {
    base: "0",
    dropdown: "100",
    drawer: "200",
    modal: "300",
    toast: "400",
    overlay: "500",
  },
});
