import { createTheme } from "@vanilla-extract/css";
import { vars } from "./contract.css";
import { color, spacing, radii, typography, motion } from "../tokens/primitives";

export const darkTheme = createTheme(vars, {
  color: {
    bg: {
      app: color.surface.base,
      canvas: color.surface.base,
      panel: color.surface.containerLow,
      elevated: color.surface.containerHigh,
      hover: color.surface.containerHighest,
      lowest: color.surface.containerLowest,
      bright: color.surface.bright,
    },
    text: {
      primary: color.onSurface.base,
      secondary: color.onSurface.variant,
      muted: color.outline.base,
      inverse: color.primary.onPrimary,
    },
    accent: {
      primary: color.primary.base,
      primaryDim: color.primary.dim,
      primaryHover: color.primary.container,
      secondary: color.secondary.base,
      tertiary: color.tertiary.base,
      cyan: "#21C7D9",
    },
    state: {
      created: color.outline.base,
      planning: color.primary.base,
      running: color.primary.base,
      cacheHit: "#21C7D9",
      completed: color.acidGreen,
      paused: color.warning.base,
      cancelled: color.outline.base,
      failed: color.error.base,
    },
    mod: {
      image: color.modality.image,
      video: color.modality.video,
      audio: color.modality.audio,
      text: color.modality.text,
      model: color.modality.model,
      system: color.modality.system,
    },
    success: { base: color.acidGreen, text: "#bbf7d0" },
    warning: { base: color.warning.base, text: color.warning.text },
    error: { base: color.error.base, text: "#fecaca" },
    outline: {
      base: color.outline.base,
      variant: color.outline.variant,
    },
  },
  font: {
    headline: typography.family.headline,
    ui: typography.family.body,
    code: typography.family.code,
    size: {
      caption: typography.size[11],
      bodySm: typography.size[12],
      body: typography.size[13],
      bodyLg: typography.size[14],
      headingSm: typography.size[16],
      heading: typography.size[20],
      headingLg: typography.size[24],
      display: typography.size[32],
    },
    weight: {
      regular: typography.weight[400],
      medium: typography.weight[500],
      semibold: typography.weight[600],
      bold: typography.weight[700],
    },
    lineHeight: {
      tight: typography.lineHeight[1.2],
      normal: typography.lineHeight[1.5],
      relaxed: typography.lineHeight[1.6],
    },
  },
  space: {
    insetXs: spacing[2],
    insetSm: spacing[3],
    insetMd: spacing[4],
    insetLg: spacing[6],
    insetXl: spacing[8],
    gapXs: spacing[2],
    gapSm: spacing[4],
    gapMd: spacing[6],
    gapLg: spacing[8],
    gapXl: spacing[12],
  },
  radius: {
    control: radii[6],
    card: radii[10],
    panel: radii[14],
    container: radii[16],
    full: radii.full,
  },
  control: {
    heightSm: "28px",
    heightMd: "32px",
    heightLg: "40px",
  },
  icon: {
    sm: "14px",
    md: "16px",
    lg: "20px",
  },
  motion: {
    durationInstant: motion.duration.instant,
    durationFast: motion.duration.fast,
    durationNormal: motion.duration.normal,
    durationSlow: motion.duration.slow,
    durationSlower: motion.duration.slower,
    easingDefault: motion.easing.default,
    easingSpring: motion.easing.spring,
    easingExit: motion.easing.exit,
  },
  shadow: {
    sm: "0 2px 4px rgba(0,0,0,0.3)",
    md: "0 4px 12px rgba(0,0,0,0.4)",
    lg: "0 12px 32px rgba(0,0,0,0.4)",
  },
  z: {
    base: "0",
    dropdown: "100",
    drawer: "200",
    modal: "300",
    toast: "400",
    overlay: "500",
  },
});
