/**
 * Spec 042 — RunEventItem TypeScript mirror.
 *
 * This file is the authoritative TS shape for the discriminated-union event
 * protocol defined by `crates/nexus-run-events`. The JSON schema at
 * `specs/042-neo-terminal-shell/contracts/run-event.schema.json` is the source
 * of truth; this mirror is generated by hand and MUST stay byte-equivalent on
 * the wire. Both `tauri_transport.ts` and `http_transport.ts` import from here.
 */

export const RUN_EVENT_SCHEMA_V1 = "nexus.run-event.v1" as const;
export type RunEventSchemaVersion = typeof RUN_EVENT_SCHEMA_V1;

export type RunId = string & { readonly __brand: "RunId" };
export type SourceId = string & { readonly __brand: "SourceId" };
export type SeqNum = number & { readonly __brand: "SeqNum" };

export const runId = (raw: string): RunId => raw as RunId;
export const sourceId = (raw: string): SourceId => raw as SourceId;
export const seqNum = (raw: number): SeqNum => raw as SeqNum;

export type LineStream = "stdout" | "stderr";

export type Severity = "trace" | "debug" | "info" | "warn" | "error";

export type PhaseName =
  | "discover"
  | "print_meta"
  | "tensors"
  | "kv_reserve"
  | "context_build"
  | "warmup"
  | "ready";

export type PhaseState = "started" | "in_progress" | "completed" | "failed";

export type MetricUnit =
  | "bytes"
  | "bytes_per_second"
  | "tokens"
  | "tokens_per_second"
  | "milliseconds"
  | "percent"
  | "count"
  | "other";

export type TensorGroup =
  | "embed"
  | "attn"
  | "ffn"
  | "norm"
  | "kv_cache"
  | "output"
  | "other";

export type AllocationTarget =
  | { kind: "gpu"; device: number }
  | { kind: "cpu" }
  | { kind: "cpu_mmap" }
  | { kind: "pinned" }
  | { kind: "mixed" };

export type WidgetKind =
  | "lattice"
  | "download"
  | "kv_cache"
  | "token_rate"
  | "file_tree"
  | "json_rpc"
  | "other";

export type ErrorReason =
  | "vram_oom"
  | "ram_oom"
  | "file_not_found"
  | "gguf_parse"
  | "corruption_suspected"
  | "quantization_mismatch"
  | "backend_init"
  | "kv_cache_init"
  | "alloc_failure_partial"
  | "user_cancelled"
  | "other";

export type GapReason =
  | "n_layer_missing"
  | "tensor_histogram_missing"
  | "transport_drop"
  | "scraper_lag"
  | "worker_crash"
  | "other";

export interface AnsiSpan {
  text: string;
  fg?: string;
  bg?: string;
  bold?: boolean;
  dim?: boolean;
  italic?: boolean;
}

interface RunEventBase {
  schema: RunEventSchemaVersion;
  seq: number;
  ts_ms: number;
  run_id: string;
  source: string;
}

export interface LineEvent extends RunEventBase {
  kind: "line";
  stream: LineStream;
  severity: Severity;
  text: string;
  spans?: AnsiSpan[];
}

export interface PhaseEvent extends RunEventBase {
  kind: "phase";
  phase: PhaseName;
  state: PhaseState;
  progress?: number;
  summary?: string;
}

export interface MetricEvent extends RunEventBase {
  kind: "metric";
  name: string;
  value: number;
  unit: MetricUnit;
  labels: Record<string, string>;
  window_ms?: number;
}

export interface TensorAllocateEvent extends RunEventBase {
  kind: "tensor_allocate";
  layer?: number;
  group: TensorGroup;
  bytes: number;
  target: AllocationTarget;
  tensor_name?: string;
  dtype?: string;
}

export interface ArtifactEvent extends RunEventBase {
  kind: "artifact";
  path: string;
  mime: string;
  bytes?: number;
  digest_sha256?: string;
}

export interface WidgetEvent extends RunEventBase {
  kind: "widget";
  widget: WidgetKind;
  props: unknown;
}

export interface ErrorEvent extends RunEventBase {
  kind: "error";
  reason: ErrorReason;
  layer?: number;
  group?: TensorGroup;
  device?: string;
  message: string;
  suggestion?: string;
}

export interface GapEvent extends RunEventBase {
  kind: "gap";
  from_seq: number;
  to_seq: number;
  reason: GapReason;
}

export interface ScraperUnknownEvent extends RunEventBase {
  kind: "scraper_unknown";
  raw_line: string;
  scraper: string;
}

export type RunEventItem =
  | LineEvent
  | PhaseEvent
  | MetricEvent
  | TensorAllocateEvent
  | ArtifactEvent
  | WidgetEvent
  | ErrorEvent
  | GapEvent
  | ScraperUnknownEvent;

export interface EventBatch {
  schema: RunEventSchemaVersion;
  run_id: string;
  batch_seq_start: number;
  batch_seq_end: number;
  events: RunEventItem[];
}

export interface RunBucket {
  start_ts_ms: number;
  end_ts_ms: number;
  counts: { info: number; warn: number; error: number };
  metrics: Record<string, { sum: number; max: number; count: number }>;
}

export interface SeqRange {
  from: number;
  to: number;
}

export interface GapReport {
  runId: RunId;
  gaps: { from_seq: number; to_seq: number; reason: GapReason; source: string }[];
}

export interface MetricSample {
  metric_name: string;
  value: number;
  ts_ms: number;
  available: boolean;
}

export const HOST_CMD_SCHEMA_V1 = "nexus.host-cmd.v1" as const;
export type HostCmdSchemaVersion = typeof HOST_CMD_SCHEMA_V1;

export interface Ok {
  schema: HostCmdSchemaVersion;
  ok: true;
}

export interface BreadcrumbInput {
  schema: HostCmdSchemaVersion;
  cwd: string;
  suffix?: string;
}

export type TrayState = "idle" | "active" | "anomaly";

export interface TraySetStateInput {
  schema: HostCmdSchemaVersion;
  state: TrayState;
  tooltip?: string;
}

export interface SubscribeInput {
  schema: HostCmdSchemaVersion;
  run_ids: string[];
  starting_from?: number;
  source_filter?: string[];
}

export interface QueryWindowInput {
  schema: HostCmdSchemaVersion;
  run_id: string;
  from_seq: number;
  to_seq: number;
  source_filter?: string[];
}

export interface QueryWindowResult {
  schema: HostCmdSchemaVersion;
  events: RunEventItem[];
  gaps: { from_seq: number; to_seq: number; reason: GapReason }[];
}

export interface BucketedInput {
  schema: HostCmdSchemaVersion;
  run_id?: string;
  bucket_ms: number;
  metric_filter?: string[];
}

export interface BucketedResult {
  schema: HostCmdSchemaVersion;
  buckets: RunBucket[];
}

export interface TuningPatchInput {
  schema: HostCmdSchemaVersion;
  deployment_id: string;
  patch: Record<string, unknown>;
  reload_after_apply: boolean;
}

export interface TuningPatchResult {
  schema: HostCmdSchemaVersion;
  applied_patch: Record<string, unknown>;
  reload_run_id?: string;
}

export interface MnemonicInput {
  schema: HostCmdSchemaVersion;
  block_id: string;
  mnemonic: string;
  prompt_header: string;
  primary_metric?: string;
}

export interface MnemonicResult {
  schema: HostCmdSchemaVersion;
  registered: boolean;
  conflict_with?: string;
}

export interface MetricsSubInput {
  schema: HostCmdSchemaVersion;
  metric_names: string[];
  window_ms: number;
}

export interface SubscribeResult {
  schema: HostCmdSchemaVersion;
  subscription_id: string;
}

export interface Subscription {
  readonly subscriptionId: string;
  unsubscribe(): Promise<void>;
}

export interface IpcErrorPayload {
  code: string;
  message: string;
  retriable: boolean;
}

export class IpcRpcError extends Error {
  public readonly code: string;
  public readonly retriable: boolean;

  constructor(payload: IpcErrorPayload) {
    super(payload.message);
    this.name = "IpcRpcError";
    this.code = payload.code;
    this.retriable = payload.retriable;
  }
}

export function isIpcErrorPayload(value: unknown): value is IpcErrorPayload {
  if (typeof value !== "object" || value === null) return false;
  const v = value as Record<string, unknown>;
  return (
    typeof v.code === "string" &&
    typeof v.message === "string" &&
    typeof v.retriable === "boolean"
  );
}
