pub mod adapter;
pub mod checksum;
pub mod compatibility;
pub mod detect;
pub mod diagnostics;
pub mod download;
pub mod error;
pub mod events;
pub mod extract;
pub mod launch_spec;
pub mod log_pipeline;
pub mod log_store;
pub mod manifest;
pub mod resolver;
pub mod settings;
pub mod settings_store;
pub mod state;
pub mod validator;

pub mod llamacpp;
pub mod tensorrt_llm_stub;

pub use adapter::{AdapterRegistry, BackendAdapter, ImplementationStatus};
pub use diagnostics::{DiagnosticRecord, FailureCategory};
pub use error::{InstallError, RuntimeAdapterError, ValidationError};
pub use events::{BackendEvent, EventPublisher};
pub use launch_spec::{LaunchSpec, generate as generate_launch_spec};
pub use manifest::install::InstallManifest;
pub use manifest::version::{ReleaseAsset, VersionManifest};
pub use resolver::{MachineDescriptor, resolve_runtime_asset};
pub use settings::{AcceleratorProfile, PortMode, RuntimeSettings};
pub use state::{RuntimeCardEvent, RuntimeCardState};
